version: 2
jobs:
  build:
    working_directory: ~/circleCItest

    docker:
    - image: anapsix/alpine-java:8_jdk_unlimited


    steps:
    - run:
        name: Add Git
        command: |
          apk update
          apk add git openssh

    - run:
        name: unit test
        command: |
          pipenv run make test

    - run:
        name: Collect All Test Reports
        command: |
          mkdir -p target/report

    - store_test_results:
        name: Store All Test Reports
        path: target/report


