version: 2
jobs:
  build:
    working_directory: ~/circleCItest

    docker:
    - image: circleci/openjdk:8u181-jdk-node-browsers-legacy


    steps:
    - run:
        name: Add Git
        command: |
          apk update
          apk add git openssh

    - run:
        name: unit test
        command: |
          mvn test

    - run:
        name: mkdir report
        command: |
          mkdir -p target/report

    - store_test_results:
        name: Store All Test Reports
        path: target/report


