version: 2
jobs:
  build:

    working_directory: ~/circleCItest

    docker:
    - image: anapsix/alpine-java:8_jdk_unlimited
      environment:

    steps:
    - run:
        command: |
          apt-get update

    - checkout

    - restore_cache:
        key: circleCItest-{{ checksum "pom.xml" }}

    - run: apt-get install maven

    - run: mvn dependency:go-offline

    - run: mvn package

    - store_test_results:
        name: Store All Test Reports
        path: target/report
