version: 2
jobs:
  test:
    working_directory: ~/circleCItest

    docker:
    - image: anapsix/alpine-java:8_jdk_unlimited


    steps:
    - run:
        name: Collect All Test Reports
        command: |
          mkdir -p target/report

    - store_test_results:
        name: Store All Test Reports
        path: target/report


