version: 2
jobs:
  build:
    working_directory: ~/circleCItest

    docker:
    - image: anapsix/alpine-java:8_jdk_unlimited

    steps:
    - store_test_results:
        name: Store All Test Reports
        path: target/surefire-reports
