version: 2
jobs:
  build:

    working_directory: ~/circleCItest

    docker:
    - image: anapsix/alpine-java:8_jdk_unlimited

    steps:

    - checkout

    - restore_cache:
        key: circleCItest-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline

    - run: mvn package

    - store_test_results:
        name: Store All Test Reports
        path: target/report
