version: 2
jobs:
  build:
    working_directory: ~/circleCItest

    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:
    - run:
        command: |
          apt-get update

    - checkout

    - run: apt-get install maven

    - run: mvn dependency:go-offline

    - run: mvn package

    - store_test_results:
        name: Store All Test Reports
        path: target/surefire-reports
