version: 2
jobs:
  build:
    working_directory: ~/circleCItest

    docker:
    - image: circleci/openjdk:8u181-node-browsers-legacy


    steps:
    - checkout

    - run:
        name: install
        command: |
          mvn -D skipTests clean install

    - run:
        name: mkdir report
        command: |
          mkdir -p target/report

    - run:
        name: unit test
        command: |
          mvn test

    - store_test_results:
        name: Store All Test Reports
        path: target/report


    show_result:
    - run:
        name: show result
        command: |
          ls /home/circleci/bitdict-test/target/report

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - show_result:
        requires:
        - build